/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type UpdatesConfigOverrideParam = any;

export type ReloadScreenOptions = any;

export function setUpdateURLAndRequestHeadersOverride(
  configOverride: UpdatesConfigOverrideParam | undefined
): any {}

export function setUpdateRequestHeadersOverride(
  requestHeaders:
    | {
        [key: string]: string;
      }
    | undefined
): any {}

export async function reload(options: ReloadScreenOptions | undefined): Promise<any> {}

export async function checkForUpdateAsync(): Promise<any> {}

export async function getExtraParamsAsync(): Promise<any> {}

export async function setExtraParamAsync(key: string, value: string | undefined): Promise<any> {}

export async function readLogEntriesAsync(maxAge: number): Promise<
  {
    [key: string]: any;
  }[]
> {
  return [];
}

export async function clearLogEntriesAsync(): Promise<any> {}

export async function fetchUpdateAsync(): Promise<any> {}

export async function showReloadScreen(options: ReloadScreenOptions | undefined): Promise<any> {}

export async function hideReloadScreen(): Promise<any> {}
