/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type SplashScreenOptions = any;

export function setOptions(options: SplashScreenOptions): any {}

export function hide(): any {}

export async function hideAsync(): Promise<any> {}

export async function internalMaybeHideAsync(): Promise<any> {}

export async function preventAutoHideAsync(): Promise<boolean> {
  return false;
}

export async function internalPreventAutoHideAsync(): Promise<any> {}
