/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type SecureStoreOptions = any;

export function getValueWithKeySync(key: string, options: SecureStoreOptions): string | undefined {
  return '';
}

export function setValueWithKeySync(
  value: string,
  key: string,
  options: SecureStoreOptions
): boolean {
  return false;
}

export function canUseBiometricAuthentication(): boolean {
  return false;
}

export async function getValueWithKeyAsync(
  key: string,
  options: SecureStoreOptions
): Promise<string | undefined> {
  return '';
}

export async function setValueWithKeyAsync(
  value: string,
  key: string,
  options: SecureStoreOptions
): Promise<boolean> {
  return false;
}

export async function deleteValueWithKeyAsync(
  key: string,
  options: SecureStoreOptions
): Promise<any> {}
