/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type TabPathPayload = any;

export type NativeLinkPreviewViewProps = {
  nextScreenId: string;
  tabPath: TabPathPayload;
  disableForceFlatten: boolean | undefined;
  onPreviewTapped: (event: any) => void;
  onPreviewTappedAnimationCompleted: (event: any) => void;
  onWillPreviewOpen: (event: any) => void;
  onDidPreviewOpen: (event: any) => void;
  onPreviewWillClose: (event: any) => void;
  onPreviewDidClose: (event: any) => void;
};

export function NativeLinkPreviewView(props: NativeLinkPreviewViewProps) {}

export type NativeLinkPreviewContentViewProps = {
  preferredContentSize: {
    [key: string]: number;
  };
};

export function NativeLinkPreviewContentView(props: NativeLinkPreviewContentViewProps) {}

export type LinkPreviewNativeActionViewProps = {
  title: string;
  icon: string | undefined;
  disabled: boolean | undefined;
  destructive: boolean | undefined;
  singleSelection: boolean;
  displayAsPalette: boolean;
  isOn: boolean | undefined;
  keepPresented: boolean | undefined;
  displayInline: boolean;
  onSelected: (event: any) => void;
};

export function LinkPreviewNativeActionView(props: LinkPreviewNativeActionViewProps) {}
