/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

type Data = any;
type SQLiteColumnValues = any;
type SQLiteColumnNames = any;

export function deleteDatabaseSync(databasePath: string): any {}

export function ensureDatabasePathExistsSync(databasePath: string): any {}

export function backupDatabaseSync(
  destDatabase: NativeDatabase,
  destDatabaseName: string,
  sourceDatabase: NativeDatabase,
  sourceDatabaseName: string
): any {}

export async function deleteDatabaseAsync(databasePath: string): Promise<any> {}

export async function importAssetDatabaseAsync(
  databasePath: string,
  assetDatabasePath: string,
  forceOverwrite: boolean
): Promise<any> {}

export async function ensureDatabasePathExistsAsync(databasePath: string): Promise<any> {}

export async function backupDatabaseAsync(
  destDatabase: NativeDatabase,
  destDatabaseName: string,
  sourceDatabase: NativeDatabase,
  sourceDatabaseName: string
): Promise<any> {}

export class NativeDatabase {
  initSync(database: NativeDatabase): any {}
  isInTransactionSync(database: NativeDatabase): boolean {
    return false;
  }
  closeSync(database: NativeDatabase): any {}
  execSync(database: NativeDatabase, source: string): any {}
  serializeSync(database: NativeDatabase, databaseName: string): any {}
  prepareSync(database: NativeDatabase, statement: NativeStatement, source: string): any {}
  createSessionSync(database: NativeDatabase, session: NativeSession, dbName: string): any {}
  loadExtensionSync(
    database: NativeDatabase,
    libPath: string,
    entryPoint: string | undefined
  ): any {}
  async initAsync(database: NativeDatabase): Promise<any> {}
  async isInTransactionAsync(database: NativeDatabase): Promise<boolean> {
    return false;
  }
  async closeAsync(database: NativeDatabase): Promise<any> {}
  async execAsync(database: NativeDatabase, source: string): Promise<any> {}
  async serializeAsync(database: NativeDatabase, databaseName: string): Promise<any> {}
  async prepareAsync(
    database: NativeDatabase,
    statement: NativeStatement,
    source: string
  ): Promise<any> {}
  async createSessionAsync(
    database: NativeDatabase,
    session: NativeSession,
    dbName: string
  ): Promise<any> {}
  async loadExtensionAsync(
    database: NativeDatabase,
    libPath: string,
    entryPoint: string | undefined
  ): Promise<any> {}
}

export class NativeStatement {
  runSync(
    statement: NativeStatement,
    database: NativeDatabase,
    bindParams: {
      [key: string]: any;
    },
    bindBlobParams: {
      [key: string]: Data;
    },
    shouldPassAsArray: boolean
  ): {
    [key: string]: any;
  } {
    return {};
  }
  stepSync(statement: NativeStatement, database: NativeDatabase): SQLiteColumnValues | undefined {
    return;
  }
  getAllSync(statement: NativeStatement, database: NativeDatabase): SQLiteColumnValues[] {
    return [];
  }
  resetSync(statement: NativeStatement, database: NativeDatabase): any {}
  getColumnNamesSync(statement: NativeStatement): SQLiteColumnNames {
    return null; // TODO: Replace with mock for value of type SQLiteColumnNames.
  }
  finalizeSync(statement: NativeStatement, database: NativeDatabase): any {}
  async runAsync(
    statement: NativeStatement,
    database: NativeDatabase,
    bindParams: {
      [key: string]: any;
    },
    bindBlobParams: {
      [key: string]: Data;
    },
    shouldPassAsArray: boolean
  ): Promise<{
    [key: string]: any;
  }> {
    return {};
  }
  async stepAsync(
    statement: NativeStatement,
    database: NativeDatabase
  ): Promise<SQLiteColumnValues | undefined> {
    return;
  }
  async getAllAsync(
    statement: NativeStatement,
    database: NativeDatabase
  ): Promise<SQLiteColumnValues[]> {
    return [];
  }
  async resetAsync(statement: NativeStatement, database: NativeDatabase): Promise<any> {}
  async getColumnNamesAsync(statement: NativeStatement): Promise<SQLiteColumnNames> {
    return null; // TODO: Replace with mock for value of type SQLiteColumnNames.
  }
  async finalizeAsync(statement: NativeStatement, database: NativeDatabase): Promise<any> {}
}

export class NativeSession {
  attachSync(session: NativeSession, database: NativeDatabase, table: string | undefined): any {}
  enableSync(session: NativeSession, database: NativeDatabase, enabled: boolean): any {}
  closeSync(session: NativeSession, database: NativeDatabase): any {}
  createChangesetSync(session: NativeSession, database: NativeDatabase): Data {
    return null; // TODO: Replace with mock for value of type Data.
  }
  createInvertedChangesetSync(session: NativeSession, database: NativeDatabase): Data {
    return null; // TODO: Replace with mock for value of type Data.
  }
  applyChangesetSync(session: NativeSession, database: NativeDatabase, changeset: Data): any {}
  invertChangesetSync(session: NativeSession, database: NativeDatabase, changeset: Data): Data {
    return null; // TODO: Replace with mock for value of type Data.
  }
  async attachAsync(
    session: NativeSession,
    database: NativeDatabase,
    table: string | undefined
  ): Promise<any> {}
  async enableAsync(
    session: NativeSession,
    database: NativeDatabase,
    enabled: boolean
  ): Promise<any> {}
  async closeAsync(session: NativeSession, database: NativeDatabase): Promise<any> {}
  async createChangesetAsync(session: NativeSession, database: NativeDatabase): Promise<Data> {
    return null; // TODO: Replace with mock for value of type Data.
  }
  async createInvertedChangesetAsync(
    session: NativeSession,
    database: NativeDatabase
  ): Promise<Data> {
    return null; // TODO: Replace with mock for value of type Data.
  }
  async applyChangesetAsync(
    session: NativeSession,
    database: NativeDatabase,
    changeset: Data
  ): Promise<any> {}
  async invertChangesetAsync(
    session: NativeSession,
    database: NativeDatabase,
    changeset: Data
  ): Promise<Data> {
    return null; // TODO: Replace with mock for value of type Data.
  }
}
