/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type MetadataOptions = any;

export function getLaunchActivity():
  | {
      [key: string]: any;
    }
  | undefined {
  return {};
}

export function createActivity(value: MetadataOptions): any {}

export function suspendActivity(id: string): any {}

export function revokeActivity(id: string): any {}

export async function clearActivitiesAsync(ids: string[]): Promise<any> {}
