name: GitHub Actions Demo
on: [push]
jobs:
  setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
  test:
    name: Run unit tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn jest --runInband
