name: GitHub Actions Demo
on: [push]
jobs:
  install:
    steps:
      - name: Install dependencies
      - run: yarn install
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
      - run: yarn jest --runInband
