name: PR cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  delete-expo-branch:
    name: Delete EAS preview branch
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock', 'patches/**') }}
      - name: Install dependencies
        run: yarn install
      - name: Delete EAS branch
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: yarn eas branch:delete ${{ github.head_ref }} --non-interactive
